#!/usr/bin/env python

import sys
import codecs

if len(sys.argv) != 2:
    print "usage: %s <encoding>" %(sys.argv[0])
    exit(1)

sys.stdin = codecs.getreader(sys.argv[1])(sys.stdin)
lines = sys.stdin.read().splitlines()

sys.stdout = codecs.getwriter(sys.argv[1])(sys.stdout)
for line in sorted(lines): print line

exit(0)
